# Generated by Django 4.2.5 on 2023-09-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltManagerConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_corps', models.ManyToManyField(to='eveonline.evecorporationinfo')),
            ],
            options={
                'verbose_name': 'Auth Reports Configuration',
                'permissions': (('basic_access', 'Can access alt manager module'), ('restricted_corps', 'Can access restricted corps.')),
                'default_permissions': [],
            },
        ),
    ]
