# Generated by Django 4.2.9 on 2024-02-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altmanagerconfiguration',
            options={'default_permissions': [], 'permissions': (('basic_access', 'Can access alt manager module'), (
                'restricted_corps', 'Can access restricted corps.'), ('su_access', 'Can access ALL corps.')), 'verbose_name': 'Auth Reports Configuration'},
        ),
    ]
