# Generated by Django 4.2.13 on 2024-07-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('altmanager', '0002_alter_altmanagerconfiguration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altmanagerconfiguration',
            options={'default_permissions': [], 'permissions': (('basic_access', 'Can access alt manager module'), ('restricted_corps', 'Can access restricted corps.'), ('su_access', 'Can access ALL corps.'), ('can_request_alt_corp', 'Can send alt corp requests'), ('can_sanction_own_corp', 'Can sanction requests from members in own corp'), ('can_sanction_all', 'Can sanction all requests'), ('can_manage_alt_corp', 'Can manage alt corp requests'), ('can_view_active_requests', 'Can view all active/current alt corp owners'), ('can_view_all_requests', 'Can view all alt corp owners')), 'verbose_name': 'Auth Reports Configuration'},
        ),
        migrations.CreateModel(
            name='AltCorpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_created=True)),
                ('corporation_name', models.CharField(max_length=250)),
                ('owner_character_name', models.CharField(help_text='The owner character name at time of claim', max_length=250)),
                ('owner_corporation_name', models.CharField(help_text='The owners corporation name at time of claim', max_length=250)),
                ('sanctioned', models.BooleanField(default=False)),
                ('sanctioner_character_name', models.CharField(help_text='The sanctioning character name at time of sanction', max_length=250)),
                ('sanctioner_corporation_name', models.CharField(help_text='The sanctioning characters corporation name at time of sanction', max_length=250)),
                ('approved', models.BooleanField(default=False)),
                ('approver_character_name', models.CharField(help_text='The approving character name at time of sanction', max_length=250)),
                ('approver_corporation_name', models.CharField(help_text='The approving characters corporation name at time of sanction', max_length=250)),
                ('pending_revoke', models.DateTimeField(blank=True, default=None, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.TextField(help_text='The revoke/pending revoke reason')),
                ('approver', models.ForeignKey(blank=True, default=None, help_text='The approver model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_approver', to='eveonline.evecharacter')),
                ('corporation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecorporationinfo')),
                ('owner', models.ForeignKey(blank=True, default=None, help_text='The owner character model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_owner', to='eveonline.evecharacter')),
                ('sanctioner', models.ForeignKey(blank=True, default=None, help_text='The owner character model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_sanctioner', to='eveonline.evecharacter')),
            ],
            options={
                'default_permissions': [],
            },
        ),
    ]
