# Generated by Django 4.2.13 on 2024-07-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('altmanager', '0003_alter_altmanagerconfiguration_options_altcorprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='altmanagerconfiguration',
            name='days_before_revoke',
            field=models.IntegerField(default=5, help_text='How many days of grace to give before revoking approvals'),
        ),
        migrations.AddField(
            model_name='altmanagerconfiguration',
            name='member_corps',
            field=models.ManyToManyField(related_name='member_corp', to='eveonline.evecorporationinfo'),
        ),
    ]
