# Generated by Django 4.2.13 on 2024-07-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altmanager', '0004_altmanagerconfiguration_days_before_revoke_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='altcorprecord',
            name='actual_members',
            field=models.IntegerField(blank=True, default=None, help_text='Member count as detected via member endpoint.', null=True),
        ),
    ]
