# Generated by Django 4.2.13 on 2024-07-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altmanager', '0005_altcorprecord_actual_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altcorprecord',
            name='approver_character_name',
            field=models.CharField(blank=True, default=None, help_text='The approving character name at time of sanction', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='altcorprecord',
            name='approver_corporation_name',
            field=models.CharField(blank=True, default=None, help_text='The approving characters corporation name at time of sanction', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='altcorprecord',
            name='owner_character_name',
            field=models.CharField(blank=True, default=None, help_text='The owner character name at time of claim', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='altcorprecord',
            name='owner_corporation_name',
            field=models.CharField(blank=True, default=None, help_text='The owners corporation name at time of claim', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='altcorprecord',
            name='revoked_reason',
            field=models.TextField(blank=True, default=None, help_text='The revoke/pending revoke reason', null=True),
        ),
        migrations.AlterField(
            model_name='altcorprecord',
            name='sanctioner_character_name',
            field=models.CharField(blank=True, default=None, help_text='The sanctioning character name at time of sanction', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='altcorprecord',
            name='sanctioner_corporation_name',
            field=models.CharField(blank=True, default=None, help_text='The sanctioning characters corporation name at time of sanction', max_length=250, null=True),
        ),
    ]
