# Generated by Django 4.2.13 on 2024-07-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('altmanager', '0006_alter_altcorprecord_approver_character_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altcorprecord',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='altcorprecord',
            name='approver_character_name',
        ),
        migrations.RemoveField(
            model_name='altcorprecord',
            name='approver_corporation_name',
        ),
        migrations.RemoveField(
            model_name='altcorprecord',
            name='corporation',
        ),
        migrations.RemoveField(
            model_name='altcorprecord',
            name='corporation_name',
        ),
        migrations.RemoveField(
            model_name='altcorprecord',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='altcorprecord',
            name='owner_character_name',
        ),
        migrations.RemoveField(
            model_name='altcorprecord',
            name='owner_corporation_name',
        ),
        migrations.RemoveField(
            model_name='altcorprecord',
            name='sanctioner',
        ),
        migrations.RemoveField(
            model_name='altcorprecord',
            name='sanctioner_character_name',
        ),
        migrations.RemoveField(
            model_name='altcorprecord',
            name='sanctioner_corporation_name',
        ),
        migrations.CreateModel(
            name='AltCorpHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_created=True)),
                ('corporation_name', models.CharField(max_length=250)),
                ('owner_character_name', models.CharField(blank=True, default=None, help_text='The owner character name at time of claim', max_length=250, null=True)),
                ('owner_corporation_name', models.CharField(blank=True, default=None, help_text='The owners corporation name at time of claim', max_length=250, null=True)),
                ('sanctioner_character_name', models.CharField(blank=True, default=None, help_text='The sanctioning character name at time of sanction', max_length=250, null=True)),
                ('sanctioner_corporation_name', models.CharField(blank=True, default=None, help_text='The sanctioning characters corporation name at time of sanction', max_length=250, null=True)),
                ('approver_character_name', models.CharField(blank=True, default=None, help_text='The approving character name at time of sanction', max_length=250, null=True)),
                ('approver_corporation_name', models.CharField(blank=True, default=None, help_text='The approving characters corporation name at time of sanction', max_length=250, null=True)),
                ('approver', models.ForeignKey(blank=True, default=None, help_text='The approver model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_approver', to='eveonline.evecharacter')),
                ('corporation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecorporationinfo')),
                ('owner', models.ForeignKey(blank=True, default=None, help_text='The owner character model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_owner', to='eveonline.evecharacter')),
                ('request', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='altmanager.altcorprecord')),
                ('sanctioner', models.ForeignKey(blank=True, default=None, help_text='The owner character model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_sanctioner', to='eveonline.evecharacter')),
            ],
            options={
                'default_permissions': [],
            },
        ),
    ]
