# Generated by Django 4.2.13 on 2024-07-07 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altmanager', '0007_remove_altcorprecord_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altcorphistory',
            name='request',
            field=models.OneToOneField(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='altmanager.altcorprecord'),
        ),
    ]
