# Generated by Django 4.2.13 on 2024-08-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('altmanager', '0009_alter_altmanagerconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altmanagerconfiguration',
            name='member_corps',
            field=models.ManyToManyField(blank=True, related_name='member_corp', to='eveonline.evecorporationinfo'),
        ),
        migrations.AlterField(
            model_name='altmanagerconfiguration',
            name='restricted_corps',
            field=models.ManyToManyField(blank=True, to='eveonline.evecorporationinfo'),
        ),
    ]
