# Generated by Django 4.2.13 on 2024-09-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altmanager', '0012_altcorptarget_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altmanagerconfiguration',
            name='management_channel_id',
            field=models.BigIntegerField(default=0, help_text='Discord Channel ID to send manager notifications to.'),
        ),
    ]
