# Generated by Django 4.2.13 on 2024-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altmanager', '0013_alter_altmanagerconfiguration_management_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInMemberCorpFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('swap_logic', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Smart Filter: Main in Member Corp',
                'verbose_name_plural': 'Smart Filter: Main in Member Corp',
            },
        ),
    ]
