# Generated by Django 4.2.17 on 2025-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('altmanager', '0017_altrecord_alter_altcorphistory_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='altmanagerconfiguration',
            name='member_alliances',
            field=models.ManyToManyField(blank=True, help_text="Alliances who's member corps are allowed to make requests", related_name='member_alliance', to='eveonline.eveallianceinfo'),
        ),
    ]
