# Generated by Django 5.2.12 on 2026-06-26 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("altmanager", "0017_altrecord_alter_altcorphistory_approver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="altcorphistory",
            name="request",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request",
                to="altmanager.altcorprecord",
            ),
        ),
        migrations.AlterField(
            model_name="altcorphistory",
            name="request_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="altcorprecord",
            name="request_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="althistory",
            name="entity_name",
            field=models.CharField(
                choices=[("Alliance", "Alliance"), ("Character", "Character")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="althistory",
            name="request",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request",
                to="altmanager.altrecord",
            ),
        ),
        migrations.AlterField(
            model_name="althistory",
            name="request_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="altrecord",
            name="request_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
